-- ELA • private user data foundation
-- Safe to review/apply later in Supabase. This file alone does not change production.

create table if not exists public.ela_profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  zodiac_sign text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ela_cycle_settings (
  user_id uuid primary key references auth.users(id) on delete cascade,
  last_period date,
  cycle_length smallint not null default 28 check (cycle_length between 15 and 60),
  period_length smallint not null default 5 check (period_length between 1 and 15),
  updated_at timestamptz not null default now()
);

create table if not exists public.ela_checkins (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  checkin_date date not null,
  mood text,
  energy smallint check (energy between 0 and 10),
  symptoms jsonb not null default '[]'::jsonb,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, checkin_date)
);

create table if not exists public.ela_wellbeing (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  entry_date date not null,
  pms smallint check (pms between 0 and 4),
  cramp smallint check (cramp between 0 and 4),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, entry_date)
);

create table if not exists public.ela_agenda (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  starts_at timestamptz not null,
  reminder_minutes integer check (reminder_minutes is null or reminder_minutes >= 0),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.ela_profiles enable row level security;
alter table public.ela_cycle_settings enable row level security;
alter table public.ela_checkins enable row level security;
alter table public.ela_wellbeing enable row level security;
alter table public.ela_agenda enable row level security;

-- Each authenticated user can only access their own rows.
do $$
declare
  t text;
begin
  foreach t in array array['ela_profiles','ela_cycle_settings','ela_checkins','ela_wellbeing','ela_agenda']
  loop
    execute format('drop policy if exists %I on public.%I', t || '_own_rows', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (auth.uid() = user_id) with check (auth.uid() = user_id)',
      t || '_own_rows', t
    );
  end loop;
end $$;

create index if not exists ela_checkins_user_date_idx on public.ela_checkins(user_id, checkin_date desc);
create index if not exists ela_wellbeing_user_date_idx on public.ela_wellbeing(user_id, entry_date desc);
create index if not exists ela_agenda_user_start_idx on public.ela_agenda(user_id, starts_at);

comment on table public.ela_checkins is 'ELA private daily check-ins. RLS isolates rows by auth.uid().';
comment on table public.ela_wellbeing is 'ELA private TPM/cramp records. RLS isolates rows by auth.uid().';
comment on table public.ela_agenda is 'ELA private agenda entries. RLS isolates rows by auth.uid().';
